"""
This is a test module for app.py.

Each function named test_* represents a test case. The name of each test case represents the behavior that is being
tested in the respective function.

When all tests are implemented, most code in app.py should be run at least once when running the test suite.
Executing a specific piece of code is the absolute minimum a test case should do. Ideally, the test makes some
assertions on the result that a specific piece of code provides. This allows us to *verify* that our web application
does what we intend it do. In a way, tests serve as an executable specification of the software we're building.
For the intents and purposes of this workshop, the tests will help us catch error that we introduce by accident.

One test case has already be implemented. Other tests are currently skipped.
Implement each test case that is currently being skipped. Remember to run `uv run pytest` frequently to check if your implementation passes.

"""

import pytest
from fastapi.testclient import TestClient

from tutorial_app.app import app, Product
from tutorial_app.json_db import DATABASE_PATH

http = TestClient(app)


def test_created_product_appears_in_product_list():
    """
    This test cases asserts that a product created with POST /products subsequently appears in the
    list of products returned by GET /products.

    The test case follows the arrange-act-assert structure [0], also known as given-when-then structure [1]given-when-then structure [1]. This means the test consists of three blocks separated by empty lines. The first block roughly consists of setting up the test environment, the second block actually runs the code that we want to test, and the third block performs assertions on the results.

    This test uses the FastAPI TestClient to make calls to the API endpoint. TestClient mimics the API of the HTTPX library, whose API docs [2] will be helpful.

    [0] Wake, Bill (2011). 3A – Arrange, Act, Assert. https://web.archive.org/web/20260106183257/https://xp123.com/3a-arrange-act-assert/
    [1] North, Dan (2006). Introducing BDD. https://web.archive.org/web/20251207002429/https://dannorth.net/blog/introducing-bdd/
    [2] https://www.python-httpx.org/
    """
    # Given
    new_product = Product(
        name="Test Product",
        description="A product for testing",
        price=1999,
    )
    # http.get performs an HTTP request
    # raise_for_status() raises an exception when the requests return code is not 2xx
    # json() converts the payload of the HTTP response into a Python dictionary
    initial_products = http.get("/products").raise_for_status().json()

    # When
    created_product = (
        http.post("/products", json=new_product.model_dump()).raise_for_status().json()
    )

    # Then
    extended_products = http.get("/products").raise_for_status().json()
    assert len(extended_products) == len(initial_products) + 1
    assert created_product in extended_products


def test_created_product_can_be_retrieved():
    # Note that product IDs are generated by the web application. The product ID is part of the response
    # to a POST /product request.
    new_product = Product(
        name="Test Product",
        description="A product for testing",
        price=1999,
    )
    created_product = (
        http.post("/products", json=new_product.model_dump()).raise_for_status().json()
    )

    retrieved_product = (
        http.get(f"/products/{created_product['id']}").raise_for_status().json()
    )

    assert retrieved_product == created_product


def test_creating_and_deleting_a_product_does_not_modify_the_product_list():
    new_product = Product(
        name="Test Product",
        description="A product for testing",
        price=1999,
    )
    initial_products = http.get("/products").raise_for_status().json()

    created_product = (
        http.post("/products", json=new_product.model_dump()).raise_for_status().json()
    )
    http.delete(f"/products/{created_product['id']}").raise_for_status()

    extended_products = http.get("/products").raise_for_status().json()
    assert len(extended_products) == len(initial_products)
    assert created_product not in extended_products


def test_similarity_between_products():
    # Unlike other API endpoints, this endpoint uses query parameters to specify product IDs
    # see https://www.python-httpx.org/compatibility/#query-parameters
    product0 = Product(
        name="Test Product",
        description="A product for testing",
        price=1999,
    )
    product1 = Product(
        name="Test Product",
        description="Another product for testing",
        price=1999,
    )
    created_product0 = (
        http.post("/products", json=product0.model_dump()).raise_for_status().json()
    )
    created_product1 = (
        http.post("/products", json=product1.model_dump()).raise_for_status().json()
    )

    similarity_response = (
        http.get(
            "/description-similarity",
            params={
                "product_id0": created_product0["id"],
                "product_id1": created_product1["id"],
            },
        )
        .raise_for_status()
        .json()
    )

    assert float(similarity_response["similarity"]) < 1.0


@pytest.fixture(autouse=True)
def test_database():
    # In reality, the tests would configure a test database.
    # This fixture restores the database file to the contents before each test case.
    old_data = DATABASE_PATH.read_bytes()
    yield
    DATABASE_PATH.write_bytes(old_data)
